apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment3
  namespace: default
  labels:
    app: testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: testapp
        image: httpd:2.5
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
