apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug2
  namespace: default
spec:
  selector:
    matchLabels:
      run: debug2
  replicas: 1
  template:
    metadata:
      labels:
        run: debug2
    spec:
      #priorityClassName: high-priority-nonpreempting
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: topology.kubernetes.io/zone
      #          operator: In
      #          values:
      #          - us-east-1b     
      containers:
      - name: debug2
        image: bdobay/python-pika:v2.2
        resources:
          requests:
            memory: "20Mi"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
