apiVersion: batch/v1
kind: Job
metadata:
  name: jobtest
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busyboxwwww
        command: ["sleep", "30"]
      restartPolicy: Never
