apiVersion: batch/v1
kind: Job
metadata:
  name: jobtest
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["echo", "This is the changed test job"]
      restartPolicy: Never
