apiVersion: batch/v1
kind: Job
metadata:
  name: jobtest
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["echo", "This is the changeddffd test job"]
      restartPolicy: Never
