apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment2
  labels:
    app: testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      serviceAccountName: testserviceaccount
      containers:
      - name: testapp
        image: amazon/aws-cli:latest
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
