apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: path2
    repoURL: https://github.com/bdobay/argotesting.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}    
